import { Montserrat } from 'next/font/google'
import './globals.css'

const montSerrat = Montserrat({ subsets: ['latin'], variable: "-font-mont" })

export const metadata = {
  title: 'Portfolio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={montSerrat.className}>{children}</body>
    </html>
  )
}
